function Home(){
    return(
        <>
        <h1>Editar...</h1>
        <table>
            <thead>
                <tr>
                    <th>Editar...</th>
                    <th>Editar...</th>
                    <th>Editar...</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Editar...</td>
                    <td>Editar...</td>
                    <td>Editar...</td>
                </tr>
                <tr>
                    <td>Editar...</td>
                    <td>Editar...</td>
                    <td>Editar...</td>
                </tr>
                <tr>
                    <td>Editar...</td>
                    <td>Editar...</td>
                    <td>Editar...</td>
                </tr>
                <tr>
                    <td>Editar...</td>
                    <td>Editar...</td>
                    <td>Editar...</td>
                </tr>
                <tr>
                    <td>Editar...</td>
                    <td>Editar...</td>
                    <td>Editar...</td>
                </tr>
            </tbody>
        </table>
        </>
    );
}
export default Home;